chore(tests): Set up CI and run clang-format
angular/blocking-proxy pull request #10
Opened 2016-10-27 23:49 UTC by mgiambalvo

2016-11-15 22:59 UTC, cnishina requested changes

2016-11-15 22:59 UTC, cnishina commented on .clang-format
> +ColumnLimit:     80
Angular is using 100 column limit. We should stay consistent.

2016-11-15 22:59 UTC, cnishina commented on circle.yml
> +    - ./node_modules/.bin/webdriver-manager update
instead of using `./node_modules/.bin/webdriver-manager udpate`, should we add a script in package.json?

package.json:

```
"scripts": {
  "webdriver-update": "webdriver-manager update"
  "webdriver-start": "webdriver-manager start"
}
```

then this command would be 

```
npm run webdriver-update
npm run webdriver-start
```

2016-11-15 23:02 UTC, mgiambalvo commented on .clang-format
> +ColumnLimit:     80
Done

2016-11-15 23:06 UTC, heathkit commented on circle.yml
> +    - ./node_modules/.bin/webdriver-manager update
How about this?

2016-11-16 01:01 UTC, cnishina approved these changes

2016-11-16 01:39 UTC, merged