Add highlight delay
angular/blocking-proxy pull request #29
Opened 2017-01-30 18:35 UTC by mgiambalvo

Also, log whenever we wait for Angular.

2017-01-30 19:04 UTC, cnishina requested changes

2017-01-30 19:04 UTC, cnishina commented on lib/angular_wait_barrier.ts
> +export class AngularWaitBarrer implements WebDriverBarrier {
Should have a JSDoc comment block about the `AngularWaitBarrer` class. Also, is it supposed to be `AngularWaitBarrer` or `AngularWaitBarrier` (spellling?)

2017-01-30 19:04 UTC, cnishina commented on lib/angular_wait_barrier.ts
> +  setRootSelector(selector: string) {
Should have a JSDoc comment block when `setRootSelector` how it is used or what it is doing.

2017-01-30 19:04 UTC, cnishina commented on lib/angular_wait_barrier.ts
> +    let commandsToWaitFor = [
nit: should use `const` over `let`?

2017-01-30 19:04 UTC, cnishina commented on lib/simple_webdriver_client.ts
> +export class SimpleWebDriverClient {
Should have a JSDoc comment block about `SimpleWebDriverClient`. Might also want to consider writing comment blocks over other public methods.

2017-01-30 22:25 UTC, mgiambalvo commented on lib/angular_wait_barrier.ts
> +export class AngularWaitBarrer implements WebDriverBarrier {
Done

2017-01-30 22:26 UTC, mgiambalvo commented on lib/angular_wait_barrier.ts
> +  setRootSelector(selector: string) {
Done

2017-01-30 22:27 UTC, mgiambalvo commented on lib/angular_wait_barrier.ts
> +    let commandsToWaitFor = [
Yeah, I should have a lint for that.

2017-01-30 22:27 UTC, mgiambalvo commented on lib/simple_webdriver_client.ts
> +export class SimpleWebDriverClient {
Done

2017-01-30 23:58 UTC, juliemr approved these changes

2017-01-30 23:58 UTC, juliemr commented on lib/simple_webdriver_client.ts
> +}
nit: add newline at eof

2017-01-30 23:58 UTC, juliemr commented on lib/client_scripts/highlight.js
> +  el.id = 'bpElementHighlight';
Can this be uglier and have some more `___`s in it?

2017-01-30 23:58 UTC, juliemr commented on lib/client_scripts/highlight.js
> + * Creates a floating transparent div at the specified location in order to highlight a particular
Nit: s/transparent/translucent

2017-01-31 00:07 UTC, mgiambalvo commented on lib/client_scripts/highlight.js
> + * Creates a floating transparent div at the specified location in order to highlight a particular
done

2017-01-31 00:08 UTC, mgiambalvo commented on lib/simple_webdriver_client.ts
> +}
done

2017-01-31 04:41 UTC, merged